include classpath("application.conf")

node-address {
  protocol = http
  host = "*"
  port = 9324
  context-path = ""
}

rest-sqs {
  enabled = true
  bind-port = 9324
  bind-hostname = "0.0.0.0"
  sqs-limits = strict
}

queues {
  order-events {
    defaultVisibilityTimeout = 10 seconds
    delay = 0 seconds
    receiveMessageWait = 0 seconds
    deadLettersQueue {
      name = "order-events-dlq"
      maxReceiveCount = 3
    }
  }
  payment-events {
    defaultVisibilityTimeout = 10 seconds
    delay = 0 seconds
    receiveMessageWait = 0 seconds
    deadLettersQueue {
      name = "payment-events-dlq"
      maxReceiveCount = 3
    }
  }
  accounting-events {
    defaultVisibilityTimeout = 10 seconds
    delay = 0 seconds
    receiveMessageWait = 0 seconds
    deadLettersQueue {
      name = "accounting-events-dlq"
      maxReceiveCount = 3
    }
  }
  notification-events {
    defaultVisibilityTimeout = 10 seconds
    delay = 0 seconds
    receiveMessageWait = 0 seconds
    deadLettersQueue {
      name = "notification-events-dlq"
      maxReceiveCount = 3
    }
  }
  marketing-events {
    defaultVisibilityTimeout = 10 seconds
    delay = 0 seconds
    receiveMessageWait = 0 seconds
    deadLettersQueue {
      name = "marketing-events-dlq"
      maxReceiveCount = 3
    }
  }
  order-events-dlq { }
  payment-events-dlq { }
  accounting-events-dlq { }
  notification-events-dlq { }
  marketing-events-dlq { }
}
