// Package catalog validates stores.template_id against the shared template
// catalog generated by libs/template-catalog (catalog.json), so a store can
// never be assigned a template the storefront/admin do not know about.
package catalog

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
)

// entry is one template's catalog metadata, matching the shape
// libs/template-catalog/src/generate-catalog.ts writes.
type entry struct {
	ID       string   `json:"id"`
	Name     string   `json:"name"`
	Category []string `json:"category"`
	Archived bool     `json:"archived"`
}

// catalogFile mirrors the top-level shape of catalog.json.
type catalogFile struct {
	Templates []entry `json:"templates"`
}

// Catalog is the set of template IDs apps/core accepts for stores.template_id.
// It is built once at process startup and never mutated afterwards.
type Catalog struct {
	validIDs map[string]bool
}

// Load reads and parses catalog.json from path. It returns an error --
// never a partially-usable Catalog -- if the file is missing, malformed, or
// has zero templates, so callers can fail fast at startup (REQ-CATALOG-04):
// a backend without its whitelist would otherwise accept any template_id
// and silently corrupt data.
func Load(path string) (*Catalog, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("catalog: read %s: %w", path, err)
	}

	var f catalogFile
	if err := json.Unmarshal(data, &f); err != nil {
		return nil, fmt.Errorf("catalog: parse %s: %w", path, err)
	}
	if len(f.Templates) == 0 {
		return nil, fmt.Errorf("catalog: %s has no templates", path)
	}

	ids := make(map[string]bool, len(f.Templates))
	for _, t := range f.Templates {
		if t.ID == "" {
			return nil, fmt.Errorf("catalog: %s has an entry with an empty id", path)
		}
		if !t.Archived {
			ids[t.ID] = true
		}
	}
	return &Catalog{validIDs: ids}, nil
}

// LoadFromWorkingDir resolves catalog.json by walking up from the process
// working directory, mirroring resolveMigrationsDir in
// internal/database/migrations.go: go test runs each package with its own
// source directory as the working directory, so a bare "./catalog.json"
// only resolves when the binary starts from apps/core itself.
func LoadFromWorkingDir() (*Catalog, error) {
	path, err := resolvePath()
	if err != nil {
		return nil, err
	}
	return Load(path)
}

func resolvePath() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", fmt.Errorf("catalog: read working directory: %w", err)
	}

	start := dir
	for {
		candidate := filepath.Join(dir, "catalog.json")
		if info, statErr := os.Stat(candidate); statErr == nil && !info.IsDir() {
			return candidate, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("catalog: no catalog.json found from %s upwards", start)
		}
		dir = parent
	}
}

// IsValid reports whether id is a known, non-archived template id.
func (c *Catalog) IsValid(id string) bool {
	if id == "" {
		return false
	}
	return c.validIDs[id]
}
